"""
seo_builder.py — Programmatic SEO Content Builder
==================================================
Pipeline:
  1. Cluster scored keywords → page-level groups (1 page per intent cluster)
  2. Generate unique content per page via Claude API
  3. Assemble full HTML from templates
  4. Build internal linking graph + sitemap fragment

All pages target kolo.xyz/crypto-card/{slug} via Cloudflare Workers KV.
"""
from __future__ import annotations

import json
import os
import re
import time
from dataclasses import dataclass, field, asdict
from typing import Optional, List, Dict

from programmatic_seo import COUNTRIES, COUNTRY_DETAILS, RU_COUNTRIES

# ── Page Cluster ──────────────────────────────────────────────────────────────

@dataclass
class PageCluster:
    """A single programmatic page targeting a cluster of related keywords."""
    slug: str
    primary_keyword: str
    secondary_keywords: List[str]
    lang: str
    country: str
    template: str       # country_card | spend_guide | persona | ru_geo | comparison
    title: str
    meta_description: str
    h1: str
    hero_subtitle: str
    country_name: str
    currency: str
    currency_name: str
    region: str
    avg_score: float
    content_html: str = ""       # generated by Claude or template
    full_html: str = ""          # final assembled page
    related_slugs: List[str] = field(default_factory=list)

    def to_dict(self):
        return asdict(self)


# ── Step 1: Cluster Keywords into Pages ───────────────────────────────────────

def cluster_keywords_to_pages(scored_keywords: List[dict]) -> List[PageCluster]:
    """
    Group scored keywords into page-level clusters.

    Core principle: ONE page per country per language.
    All keyword variants for that country (card, spend, pay, etc.) become
    secondary keywords on the same page — no fragmentation.

    Persona pages (digital nomad, freelancer, etc.) are global and get their own page.
    """
    # Group by (country, lang) for geo pages, or (persona, lang) for persona pages
    groups: Dict[str, List[dict]] = {}

    for kw in scored_keywords:
        country = kw.get("country", "global")
        lang = kw.get("lang", "en")
        keyword = kw.get("keyword", "")

        kw_lower = keyword.lower()

        # Persona pages = their own cluster (global, not per-country)
        if any(p in kw_lower for p in ["freelancer", "nomad", "expat"]):
            persona = "digital-nomad"
            for p in ["freelancer", "nomad", "expat"]:
                if p in kw_lower:
                    persona = p
                    break
            key = f"persona|{persona}|{lang}"
        elif country != "global":
            # ALL country keywords → single page per country+lang
            key = f"country|{country}|{lang}"
        else:
            # Global comparison/generic keywords
            key = f"global|generic|{lang}"

        if key not in groups:
            groups[key] = []
        groups[key].append(kw)

    # Convert groups to PageClusters
    clusters = []
    for key, kws in groups.items():
        bucket, identifier, lang = key.split("|")

        # Sort by score, best = primary keyword
        kws.sort(key=lambda x: -x.get("quality_score", 0))
        primary = kws[0]
        secondary = [k["keyword"] for k in kws[1:]]

        # Determine country and template from bucket type
        if bucket == "country":
            country = identifier
            template = "ru_geo" if lang == "ru" else "country_card"
        elif bucket == "persona":
            country = "global"
            template = "persona"
        else:
            country = "global"
            template = "comparison"

        # Get country metadata
        cdata = COUNTRIES.get(country, {})
        country_name = cdata.get("name", country)
        cdetails = COUNTRY_DETAILS.get(country, {})
        currency = cdetails.get("currency", "")
        currency_name = cdetails.get("currency_name", "")
        region = cdetails.get("region", "")

        # Generate slug — ONE slug per country+lang
        slug_country = country_name.lower().replace(" ", "-")
        if bucket == "country":
            if lang == "ru":
                slug = f"ru/{slug_country}"
            else:
                slug = slug_country
        elif bucket == "persona":
            slug = identifier  # "freelancer", "digital-nomad", etc.
        else:
            slug = f"compare-crypto-cards" if lang == "en" else f"ru/compare"

        # Title & meta
        title, meta, h1, subtitle = _generate_meta(template, country_name, currency_name, lang, primary["keyword"])

        avg_score = round(sum(k.get("quality_score", 0) for k in kws) / len(kws), 3)

        cluster = PageCluster(
            slug=slug,
            primary_keyword=primary["keyword"],
            secondary_keywords=secondary[:7],  # max 7 secondary
            lang=lang,
            country=country,
            template=template,
            title=title,
            meta_description=meta,
            h1=h1,
            hero_subtitle=subtitle,
            country_name=country_name,
            currency=currency,
            currency_name=currency_name,
            region=region,
            avg_score=avg_score,
        )
        clusters.append(cluster)

    clusters.sort(key=lambda x: -x.avg_score)
    return clusters


def _generate_meta(template: str, country: str, currency: str, lang: str, keyword: str):
    """Generate title, meta_description, h1, hero_subtitle for a page cluster."""
    if template == "country_card":
        title = f"Crypto Visa Card in {country} — Spend USDT & Bitcoin | Kolo"
        meta = (f"Get a crypto Visa card that works in {country}. Convert USDT, BTC, and ETH to "
                f"{currency or 'local currency'} instantly at any Visa merchant. Low fees, no bank needed.")
        h1 = f"Crypto Visa Card in {country}"
        subtitle = f"Convert your crypto to {currency or 'local currency'} and spend anywhere in {country}"

    elif template == "spend_guide":
        title = f"How to Spend Crypto in {country} — Complete Guide 2026 | Kolo"
        meta = (f"Step-by-step guide to spending cryptocurrency in {country}. Compare crypto cards, "
                f"P2P exchanges, and direct conversion to {currency or 'local currency'}.")
        h1 = f"How to Spend Crypto in {country}"
        subtitle = f"Everything you need to know about using Bitcoin and USDT in {country}"

    elif template == "persona":
        persona = "Digital Nomads"
        for p, label in [("freelancer", "Freelancers"), ("nomad", "Digital Nomads"),
                         ("expat", "Expats"), ("business", "Businesses")]:
            if p in keyword.lower():
                persona = label
                break
        title = f"Best Crypto Card for {persona} — Spend Anywhere | Kolo"
        meta = (f"The best crypto Visa card for {persona.lower()}. Spend USDT, BTC, ETH in "
                f"60+ countries with instant conversion and low fees.")
        h1 = f"Best Crypto Card for {persona}"
        subtitle = f"Built for {persona.lower()} who earn and spend in crypto"

    elif template in ("ru_geo", "ru_generic"):
        if country and country != "global":
            ru_country = country
            title = f"Крипто карта в {ru_country} — USDT и Bitcoin Visa | Kolo"
            meta = (f"Криптовалютная Visa карта для {ru_country}. Мгновенная конвертация USDT, BTC и ETH. "
                    f"Работает в 60+ странах. Без банковского счёта.")
            h1 = f"Крипто карта в {ru_country}"
            subtitle = f"Тратьте криптовалюту в {ru_country} как обычные деньги"
        else:
            title = "Лучшая крипто карта 2026 — USDT Visa карта | Kolo"
            meta = ("Лучшая криптовалютная Visa карта 2026 года. Мгновенная конвертация USDT, BTC, ETH. "
                    "Работает в 60+ странах. Низкие комиссии.")
            h1 = "Лучшая крипто карта 2026"
            subtitle = "Мгновенная конвертация криптовалюты в фиат с Visa картой Kolo"
    else:
        title = f"{keyword.title()} — Kolo Crypto Visa Card"
        meta = f"{keyword.title()}. Compare crypto cards and find the best option for spending USDT, BTC, and ETH worldwide."
        h1 = keyword.title()
        subtitle = "Compare and choose the right crypto card for your needs"

    return title, meta, h1, subtitle


# ── Step 2: Content Generation via Claude ─────────────────────────────────────

_CONTENT_SYSTEM_PROMPT = """You are a senior SEO content writer for Kolo, a crypto Visa card company.
Write unique, helpful content for a programmatic SEO page.

Rules:
- Write in clean HTML (use <h2>, <h3>, <p>, <ul>, <ol>, <section> tags)
- NO generic fluff. Every sentence must be useful.
- Include specific details about the country/use-case where applicable
- Naturally incorporate the primary and secondary keywords (don't stuff)
- Write 600-1000 words of body content
- Include a "How It Works" section with numbered steps
- Include a features/benefits section
- Include 3-4 FAQ items using <details>/<summary> tags
- Tone: clear, direct, slightly informal. Like a knowledgeable friend explaining.
- DO NOT mention competitors by name
- DO NOT use words: revolutionary, game-changing, seamlessly, leverage, cutting-edge
- DO NOT start any section with "In today's" or "In the world of"
- Kolo is available on iOS, Android, Telegram mini-app, and web
- Kolo supports USDT (TRC-20, ERC-20), BTC, ETH, TRX
- Cards work at 60M+ Visa merchants worldwide
- DO NOT include the <h1> — it's already in the template
- Return ONLY the HTML content blocks, no wrapper"""

_RU_CONTENT_SYSTEM_PROMPT = """Ты — старший SEO-копирайтер для Kolo, крипто Visa карты.
Пиши уникальный полезный контент для SEO-страницы на русском языке.

Правила:
- Пиши на чистом HTML (теги <h2>, <h3>, <p>, <ul>, <ol>, <section>)
- НЕ пиши общие фразы. Каждое предложение должно быть полезным.
- Используй конкретные детали о стране/кейсе
- Естественно включай ключевые слова (не переспамь)
- Объём: 600-1000 слов
- Включи раздел "Как это работает" с нумерованными шагами
- Включи раздел преимуществ
- Включи 3-4 FAQ с тегами <details>/<summary>
- Тон: чёткий, прямой, слегка неформальный
- НЕ упоминай конкурентов по имени
- НЕ используй слова: революционный, инновационный, бесшовный
- Kolo работает на iOS, Android, Telegram мини-приложение и веб
- Поддерживает USDT (TRC-20, ERC-20), BTC, ETH, TRX
- Карта работает в 60M+ терминалах Visa по всему миру
- НЕ включай <h1> — он уже в шаблоне
- Верни ТОЛЬКО HTML-блоки контента"""


def generate_page_content(
    cluster: PageCluster,
    api_key: str,
    model: str = "claude-haiku-4-5-20251001",
    max_tokens: int = 2048,
) -> str:
    """
    Generate unique content for a page cluster using Claude API.
    Returns HTML content blocks string.
    Cost: ~$0.002-0.005 per page with Haiku.
    """
    from anthropic import Anthropic

    system = _RU_CONTENT_SYSTEM_PROMPT if cluster.lang == "ru" else _CONTENT_SYSTEM_PROMPT

    user_msg = f"""Write content for this programmatic SEO page:

**Primary keyword:** {cluster.primary_keyword}
**Secondary keywords:** {', '.join(cluster.secondary_keywords[:5])}
**Country:** {cluster.country_name}
**Currency:** {cluster.currency_name} ({cluster.currency})
**Region:** {cluster.region}
**Template type:** {cluster.template}
**Language:** {cluster.lang}

**Page context:**
- This page targets people searching for "{cluster.primary_keyword}"
- They want to know how to get/use a crypto Visa card in {cluster.country_name}
- Kolo converts crypto to {cluster.currency_name or 'local currency'} at point of sale
- Cards are available in {cluster.country_name} (it's a supported market)

Write the HTML content blocks now."""

    client = Anthropic(api_key=api_key)
    try:
        resp = client.messages.create(
            model=model,
            max_tokens=max_tokens,
            system=system,
            messages=[{"role": "user", "content": user_msg}],
        )
        return resp.content[0].text
    except Exception as e:
        return f"<p>[Content generation error: {e}]</p>"


def generate_content_batch(
    clusters: List[PageCluster],
    api_key: str,
    model: str = "claude-haiku-4-5-20251001",
    delay: float = 1.0,
    progress_callback=None,
) -> List[PageCluster]:
    """Generate content for multiple clusters. Returns clusters with content_html filled."""
    for i, cluster in enumerate(clusters):
        cluster.content_html = generate_page_content(cluster, api_key, model=model)
        if progress_callback:
            progress_callback(i + 1, len(clusters))
        if i < len(clusters) - 1:
            time.sleep(delay)
    return clusters


# ── Step 3: Assemble Full HTML ────────────────────────────────────────────────

_TEMPLATE_DIR = os.path.join(os.path.dirname(__file__), "templates")


def _load_template() -> str:
    """Load the base HTML template."""
    path = os.path.join(_TEMPLATE_DIR, "base.html")
    with open(path, "r") as f:
        return f.read()


def _build_json_ld(cluster: PageCluster) -> str:
    """Build JSON-LD structured data for a page."""
    ld = {
        "@context": "https://schema.org",
        "@type": "FinancialProduct",
        "name": "Kolo Crypto Visa Card",
        "description": cluster.meta_description,
        "provider": {
            "@type": "Organization",
            "name": "Kolo",
            "url": "https://kolo.xyz"
        },
        "url": f"https://kolo.xyz/crypto-card/{cluster.slug}",
        "category": "Cryptocurrency Debit Card",
    }
    if cluster.country != "global":
        ld["areaServed"] = {
            "@type": "Country",
            "name": cluster.country_name,
        }
    # Add FAQ schema if content has <details> tags
    if "<details>" in cluster.content_html:
        faq_items = re.findall(
            r'<summary>(.*?)</summary>.*?<p>(.*?)</p>',
            cluster.content_html, re.DOTALL
        )
        if faq_items:
            ld["mainEntity"] = [
                {
                    "@type": "Question",
                    "name": q.strip(),
                    "acceptedAnswer": {"@type": "Answer", "text": a.strip()},
                }
                for q, a in faq_items[:5]
            ]
            # Also add FAQPage type
            ld = [ld, {
                "@context": "https://schema.org",
                "@type": "FAQPage",
                "mainEntity": ld["mainEntity"],
            }]

    return json.dumps(ld, indent=2, ensure_ascii=False)


def _build_related_html(cluster: PageCluster, all_clusters: List[PageCluster]) -> str:
    """Build related pages section with internal links."""
    related = []
    for other in all_clusters:
        if other.slug == cluster.slug:
            continue
        # Same region or same template = related
        same_region = other.region == cluster.region and cluster.region
        same_template = other.template == cluster.template
        same_lang = other.lang == cluster.lang
        if (same_region or same_template) and same_lang:
            related.append(other)
        if len(related) >= 6:
            break

    if not related:
        return ""

    cards = []
    for r in related[:4]:
        cards.append(
            f'<a class="related-card" href="/crypto-card/{r.slug}">'
            f'<h3>{r.h1}</h3>'
            f'<p>{r.meta_description[:80]}...</p></a>'
        )

    return (
        '<section class="related"><h2>Related Guides</h2>'
        f'<div class="related-grid">{"".join(cards)}</div></section>'
    )


def _build_breadcrumb(cluster: PageCluster) -> str:
    """Build breadcrumb middle section."""
    if cluster.lang == "ru":
        return '<a href="/crypto-card/ru/best-crypto-card">Крипто карта</a> &rsaquo; '
    elif cluster.template == "persona":
        return '<a href="/crypto-card/digital-nomad">Crypto Cards</a> &rsaquo; '
    else:
        return '<a href="/crypto-card/uk">Crypto Cards</a> &rsaquo; '


def assemble_page(cluster: PageCluster, all_clusters: List[PageCluster]) -> str:
    """Assemble the final HTML page from template + generated content."""
    template = _load_template()

    # Build components
    json_ld = _build_json_ld(cluster)
    related_html = _build_related_html(cluster, all_clusters)
    breadcrumb_mid = _build_breadcrumb(cluster)

    # Hreflang (link EN and RU versions if both exist)
    hreflang = ""
    for other in all_clusters:
        if other.country == cluster.country and other.template == cluster.template and other.lang != cluster.lang:
            hreflang += f'<link rel="alternate" hreflang="{other.lang}" href="https://kolo.xyz/crypto-card/{other.slug}">\n    '
    hreflang += f'<link rel="alternate" hreflang="{cluster.lang}" href="https://kolo.xyz/crypto-card/{cluster.slug}">\n    '
    hreflang += f'<link rel="alternate" hreflang="x-default" href="https://kolo.xyz/crypto-card/{cluster.slug}">'

    # Separate FAQ from content (if FAQ is in content_html, extract it)
    content = cluster.content_html
    faq_html = ""
    faq_match = re.search(r'(<section class="faq">.*?</section>)', content, re.DOTALL)
    if faq_match:
        faq_html = faq_match.group(1)
        content = content[:faq_match.start()] + content[faq_match.end():]
    elif "<details>" in content:
        # Wrap loose FAQ items
        details_parts = re.findall(r'(<details>.*?</details>)', content, re.DOTALL)
        if details_parts:
            faq_html = '<section class="faq"><h2>FAQ</h2>' + ''.join(details_parts) + '</section>'
            for part in details_parts:
                content = content.replace(part, '')

    # Replace template variables
    html = template
    replacements = {
        "{{lang}}": cluster.lang,
        "{{title}}": cluster.title,
        "{{meta_description}}": cluster.meta_description,
        "{{slug}}": cluster.slug,
        "{{h1}}": cluster.h1,
        "{{hero_subtitle}}": cluster.hero_subtitle,
        "{{json_ld}}": json_ld,
        "{{hreflang_tags}}": hreflang,
        "{{breadcrumb_middle}}": breadcrumb_mid,
        "{{breadcrumb_current}}": cluster.h1,
        "{{content_blocks}}": content,
        "{{faq_section}}": faq_html,
        "{{related_pages}}": related_html,
    }
    for key, val in replacements.items():
        html = html.replace(key, val)

    cluster.full_html = html
    return html


def build_all_pages(clusters: List[PageCluster]) -> List[PageCluster]:
    """Assemble all pages with internal linking."""
    for cluster in clusters:
        assemble_page(cluster, clusters)
        # Set related slugs for the manifest
        related = []
        for other in clusters:
            if other.slug != cluster.slug and other.region == cluster.region and other.lang == cluster.lang:
                related.append(other.slug)
        cluster.related_slugs = related[:6]
    return clusters


# ── Step 4: Manifest & Sitemap ────────────────────────────────────────────────

def build_manifest(clusters: List[PageCluster]) -> dict:
    """Build a manifest of all pages for KV storage and sitemap generation."""
    pages = []
    for c in clusters:
        pages.append({
            "slug": c.slug,
            "title": c.title,
            "lang": c.lang,
            "country": c.country,
            "template": c.template,
            "primary_keyword": c.primary_keyword,
            "keywords_count": 1 + len(c.secondary_keywords),
            "avg_score": c.avg_score,
            "related": c.related_slugs[:4],
        })
    return {
        "total_pages": len(pages),
        "pages": pages,
    }


def build_sitemap_fragment(clusters: List[PageCluster]) -> str:
    """Build XML sitemap fragment for programmatic pages."""
    from datetime import date
    today = date.today().isoformat()

    urls = []
    for c in clusters:
        urls.append(
            f"  <url>\n"
            f"    <loc>https://kolo.xyz/crypto-card/{c.slug}</loc>\n"
            f"    <lastmod>{today}</lastmod>\n"
            f"    <changefreq>monthly</changefreq>\n"
            f"    <priority>0.7</priority>\n"
            f"  </url>"
        )
    return "\n".join(urls)


# ── Export to local files ─────────────────────────────────────────────────────

def export_pages_local(clusters: List[PageCluster], base_dir: str = None):
    """Export all pages as HTML files to local directory for review."""
    if base_dir is None:
        base_dir = os.path.join(os.path.dirname(__file__), "pages")
    os.makedirs(base_dir, exist_ok=True)

    for c in clusters:
        # Handle nested slugs (e.g., ru/oae)
        page_dir = os.path.join(base_dir, c.slug)
        os.makedirs(page_dir, exist_ok=True)
        filepath = os.path.join(page_dir, "index.html")
        with open(filepath, "w") as f:
            f.write(c.full_html)

    # Write manifest
    manifest = build_manifest(clusters)
    with open(os.path.join(base_dir, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    # Write sitemap fragment
    sitemap = build_sitemap_fragment(clusters)
    with open(os.path.join(base_dir, "sitemap_fragment.xml"), "w") as f:
        f.write(sitemap)

    return len(clusters)
