"""Page 11 — Programmatic SEO: keyword matrix → validate → compete → build pages."""
from __future__ import annotations

import os
import csv
import json
from datetime import date
import streamlit as st
import pandas as pd

from programmatic_seo import (
    generate_keyword_matrix, score_and_filter_keywords,
    validate_keywords_autocomplete, COUNTRIES,
)
from keyword_research import get_google_autocomplete, expand_keywords_serpapi
from seo_builder import (
    cluster_keywords_to_pages, generate_content_batch,
    build_all_pages, build_manifest, build_sitemap_fragment,
    export_pages_local,
)


def _generate_designer_brief(clusters, base_dir):
    """Generate a plug-and-play brief for the Webflow Designer."""
    manifest = build_manifest(clusters)
    sitemap_frag = build_sitemap_fragment(clusters)

    page_table = "\n".join(
        f"| `/crypto-card/{c.slug}` | {c.lang} | {c.country_name} | {c.primary_keyword} | +{len(c.secondary_keywords)} keywords |"
        for c in clusters
    )

    brief = f"""# Webflow Designer Brief — Programmatic SEO Pages
## Plug & Play Setup Guide

### What This Is
{len(clusters)} pre-built SEO pages for kolo.xyz/crypto-card/{{slug}}.
All content, titles, meta descriptions, and HTML are pre-generated.

---

### Step 1: Create CMS Collection (5 min)
1. Open Webflow Designer → **CMS** → **+ New Collection**
2. Name: **Crypto Card Pages** / Slug prefix: **crypto-card**
3. Add fields: Name, Slug, SEO Title, SEO Description, H1, Hero Subtitle, Body Content (Rich Text), Language, Country, Primary Keyword, Related Pages

### Step 2: Design the Template Page (15 min)
1. Build layout: Nav → Hero (H1 + subtitle) → Body Content → CTA → Related pages → Footer
2. Bind SEO Title + Description. Publish template.

### Step 3: Import Content (10 min)
**Option A — Manual:** Copy from `pages/{{slug}}/index.html`
**Option B — CSV Import:** Upload `pages/cms_import.csv` to Webflow CMS
**Option C — Webflow API:** Run deploy script from SEO agent

### Step 4: Publish
Review a few pages → Publish all → Check kolo.xyz/crypto-card/uae

---

### Page Summary
{page_table}

---
Generated by Kolo SEO Agent · {date.today().isoformat()}
"""

    brief_path = os.path.join(base_dir, "DESIGNER_BRIEF.md")
    with open(brief_path, "w") as f:
        f.write(brief)

    csv_path = os.path.join(base_dir, "cms_import.csv")
    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["Name", "Slug", "SEO Title", "SEO Description", "H1", "Hero Subtitle", "Language", "Country", "Primary Keyword"])
        for c in clusters:
            w.writerow([c.h1, c.slug, c.title, c.meta_description, c.h1, c.hero_subtitle, c.lang, c.country_name, c.primary_keyword])

    manifest_path = os.path.join(base_dir, "manifest.json")
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    sitemap_path = os.path.join(base_dir, "sitemap_fragment.xml")
    with open(sitemap_path, "w") as f:
        f.write(sitemap_frag)


def page_programmatic_seo():
    st.title("🚀 SEO Factory")
    st.caption("Find Google keywords to target → turn them into articles or auto-built landing pages")

    st.info("""
**What this does:** Discovers long-tail keywords people type into Google (e.g. *"crypto card for freelancers in UAE"*)
and either exports them as a topic list for your writers, or auto-builds landing pages on kolo.xyz.

**Not for AI visibility** — if you want to check whether Kolo shows up in ChatGPT/Perplexity answers,
use the **GEO Tracker** page instead.
""")

    # ── Quick Lookup: single keyword, instant Autocomplete + PAA ───────────
    with st.expander("🔎 Quick Lookup — check any single keyword", expanded=False):
        st.caption("Instantly pull Google Autocomplete (free) and People Also Ask / Related Searches (1 SerpAPI credit).")
        ql_kw = st.text_input("Keyword", value="", placeholder="e.g. crypto card uae", key="ql_kw")
        ql_c1, ql_c2 = st.columns(2)
        with ql_c1:
            ql_lang = st.selectbox("Language", ["en", "ru", "it", "es", "pl", "pt", "id", "ro"], key="ql_lang")
        with ql_c2:
            ql_country = st.text_input("Country code (optional)", value="", placeholder="gb, ae, it...", key="ql_country")

        btn_ac, btn_paa = st.columns(2)
        with btn_ac:
            run_ac = st.button("🔍 Autocomplete", use_container_width=True, disabled=not ql_kw.strip(), key="ql_btn_ac")
        with btn_paa:
            serp_key = st.session_state.get("serpapi_key")
            run_paa = st.button("💬 People Also Ask (SerpAPI)", use_container_width=True,
                                 disabled=not ql_kw.strip() or not serp_key, key="ql_btn_paa",
                                 help="Needs SerpAPI key in sidebar" if not serp_key else None)

        if run_ac:
            with st.spinner("Querying Google Autocomplete..."):
                suggestions = get_google_autocomplete(ql_kw.strip(), language=ql_lang, country=ql_country or "")
            st.session_state["ql_ac_results"] = {"seed": ql_kw, "suggestions": suggestions}

        if run_paa:
            with st.spinner("Querying SerpAPI..."):
                try:
                    expansion = expand_keywords_serpapi(serp_key, ql_kw.strip())
                    st.session_state["ql_paa_results"] = {"seed": ql_kw, **expansion}
                except Exception as e:
                    st.error(f"SerpAPI error: {e}")

        # Render results side by side
        if st.session_state.get("ql_ac_results") or st.session_state.get("ql_paa_results"):
            res_ac_col, res_paa_col = st.columns(2)
            with res_ac_col:
                ac = st.session_state.get("ql_ac_results")
                if ac:
                    st.markdown(f"**Autocomplete — `{ac['seed']}`**")
                    sugg = ac.get("suggestions") or []
                    if sugg:
                        for s in sugg:
                            st.markdown(f"- {s}")
                    else:
                        st.info("No suggestions returned")
            with res_paa_col:
                paa = st.session_state.get("ql_paa_results")
                if paa:
                    st.markdown(f"**People Also Ask — `{paa['seed']}`**")
                    questions = paa.get("people_also_ask") or []
                    if questions:
                        for q in questions:
                            st.markdown(f"- {q}")
                    else:
                        st.info("No PAA found")
                    related = paa.get("related_searches") or []
                    if related:
                        st.markdown("**Related searches**")
                        for r in related:
                            st.markdown(f"- {r}")

    with st.expander("ℹ️ How the 3 steps work", expanded=False):
        st.markdown("""
1. **Keyword Matrix** — generate patterns like `{crypto} card in {country}` × markets × languages. Free.
2. **Autocomplete Validation** — check each keyword against Google Autocomplete to prove real demand. Free.
3. **Build Pages** — cluster keywords into pages (1 per country+language), have Claude write content, export HTML. ~$0.08 for ~41 pages.

👉 After Step 2 you can also just **download the CSV** and hand it to your PR writers instead of building pages.
""")

    tab_matrix, tab_validate, tab_build = st.tabs([
        "1️⃣ Keyword Matrix", "2️⃣ Autocomplete Validation", "3️⃣ Build Pages"
    ])

    # ── TAB 1: Keyword Matrix ─────────────────────────────────────
    with tab_matrix:
        st.subheader("Keyword Matrix Generator")
        st.info("Combines countries × cryptos × use cases × modifiers. **Zero API cost.**")

        col1, col2, col3 = st.columns(3)
        with col1:
            tiers = st.multiselect("Country tiers", [1, 2, 3], default=[1, 2])
        with col2:
            include_ru = st.checkbox("Include Russian keywords", value=True, help="RU = 2x LTV")
        with col3:
            max_kw = st.number_input("Max keywords", 100, 5000, 2000, step=100)

        col_s1, col_s2 = st.columns(2)
        with col_s1:
            min_score = st.slider("Min keyword score", 0.3, 0.75, 0.45, 0.05)
        with col_s2:
            min_pattern_avg = st.slider("Min pattern avg score", 0.3, 0.75, 0.5, 0.05)

        if st.button("🔧 Generate → Score → Dedup → Filter", type="primary"):
            with st.spinner("Generating keyword combinations..."):
                raw_matrix = generate_keyword_matrix(tiers=tiers, include_ru=include_ru, max_combos=max_kw)
            with st.spinner(f"Scoring → deduplicating → evaluating ({len(raw_matrix):,} keywords)..."):
                result = score_and_filter_keywords(raw_matrix, min_score=min_score, min_pattern_avg=min_pattern_avg)
                st.session_state["pseo_matrix"] = result["kept"]
                st.session_state["pseo_score_result"] = result

        if "pseo_score_result" in st.session_state:
            result = st.session_state["pseo_score_result"]
            stats = result["stats"]

            st.success(f"**{stats['kept']}** keywords kept · **{stats['rejected']}** rejected ({stats['rejection_rate']}% filtered)")

            st.subheader("Pipeline Funnel")
            col_a, col_b, col_c, col_d = st.columns(4)
            col_a.metric("Raw Generated", stats["total_raw"])
            col_b.metric("After Scoring", stats["after_scoring"])
            col_c.metric("After Dedup", stats["after_dedup"], delta=f"-{result['dedup_stats']['duplicates_removed']} dupes")
            col_d.metric("After Pattern Eval", stats["after_pattern_eval"])

            col_e, col_f, col_g = st.columns(3)
            col_e.metric("Avg Score", stats["avg_score"])
            col_f.metric("Filter Rate", f"{stats['rejection_rate']}%")
            col_g.metric("Intent Clusters", result["dedup_stats"]["clusters"])

            st.subheader("Score Distribution")
            dist = stats["score_distribution"]
            dist_df = pd.DataFrame([{"range": k, "count": v} for k, v in dist.items()])
            st.bar_chart(dist_df.set_index("range"))

            st.subheader("Pattern Evaluation")
            pat_eval = result.get("pattern_eval", {})
            pat_rows = [{"Pattern": p, "Keywords": ps["count"], "Avg Score": ps["avg_score"],
                         "Top": ps["top_score"], "Bottom": ps["bottom_score"],
                         "Status": "✅" if ps["avg_score"] >= min_pattern_avg else "❌ dropped"}
                        for p, ps in sorted(pat_eval.items(), key=lambda x: -x[1]["avg_score"])]
            st.dataframe(pd.DataFrame(pat_rows), hide_index=True)

            st.subheader("Kept Keywords by Pattern")
            for pattern, count in sorted(stats["by_pattern_count"].items(), key=lambda x: -x[1]):
                with st.expander(f"**{pattern}** — {count} keywords"):
                    pat_df = pd.DataFrame(result["by_pattern"][pattern])
                    display_cols = [c for c in ["keyword", "lang", "country", "quality_score",
                                                "intent_score", "natural_score", "scale_score",
                                                "market_score", "cluster_size", "alternates"] if c in pat_df.columns]
                    st.dataframe(pat_df[display_cols].head(40), height=300)

            with st.expander(f"Rejected keywords ({len(result['rejected'])} total)", expanded=False):
                rej_df = pd.DataFrame(result["rejected"])
                display_cols = [c for c in ["keyword", "quality_score", "reject_reason", "intent_score", "natural_score"] if c in rej_df.columns]
                st.dataframe(rej_df[display_cols].head(40), height=200)

    # ── TAB 2: Autocomplete Validation ────────────────────────────
    with tab_validate:
        st.subheader("Google Autocomplete Validation")
        st.info("Checks if Google suggests these keywords → real demand. **100% free.**")

        if "pseo_matrix" not in st.session_state:
            st.warning("Generate & score a keyword matrix first (Tab 1)")
        else:
            matrix = st.session_state["pseo_matrix"]
            st.write(f"**{len(matrix):,}** keywords ready for validation")

            col1, col2 = st.columns(2)
            with col1:
                batch_size = st.number_input("Batch size", 10, 500, 100, step=10)
            with col2:
                start_from = st.number_input("Start from index", 0, len(matrix) - 1, 0, step=10)

            if st.button("✅ Validate via Autocomplete", type="primary"):
                batch = matrix[start_from:start_from + batch_size]
                progress = st.progress(0, text="Checking Google Autocomplete...")
                def _update(i, total):
                    progress.progress(i / total, text=f"Checking {i}/{total}...")
                validated = validate_keywords_autocomplete(batch, delay=0.15, progress_callback=_update)
                progress.progress(1.0, text="Done!")
                existing = st.session_state.get("pseo_validated", [])
                existing.extend(validated)
                st.session_state["pseo_validated"] = existing

        if "pseo_validated" in st.session_state:
            validated = st.session_state["pseo_validated"]
            vdf = pd.DataFrame(validated)

            strong = vdf[vdf["demand_signal"] == "strong"]
            medium = vdf[vdf["demand_signal"] == "medium"]
            weak = vdf[vdf["demand_signal"] == "weak"]
            none_ = vdf[vdf["demand_signal"] == "none"]

            col_a, col_b, col_c, col_d = st.columns(4)
            col_a.metric("🟢 Strong", len(strong))
            col_b.metric("🟡 Medium", len(medium))
            col_c.metric("🟠 Weak", len(weak))
            col_d.metric("🔴 No Signal", len(none_))

            winners = vdf[vdf["demand_signal"].isin(["strong", "medium"])].sort_values("autocomplete_hits", ascending=False)
            st.write(f"**{len(winners)}** keywords with demand signal")
            with st.expander(f"Keywords with demand ({len(winners)})", expanded=True):
                display_cols = ["keyword", "lang", "country", "demand_signal", "autocomplete_hits"]
                extra = [c for c in ["autocomplete_suggestions"] if c in winners.columns]
                st.dataframe(winners[display_cols + extra].head(100), height=400)

            st.divider()
            st.markdown("### Next step — choose output")
            col_exp, col_build = st.columns(2)
            with col_exp:
                st.markdown("**📥 Use for articles**")
                st.caption("Hand these keywords to writers. Also loadable in PR Generator / Content Plan.")
                st.download_button("Download keywords CSV",
                    data=winners[display_cols + extra].to_csv(index=False),
                    file_name=f"keywords_{pd.Timestamp.now().strftime('%Y%m%d')}.csv",
                    mime="text/csv", use_container_width=True)
            with col_build:
                st.markdown("**🏗️ Auto-build landing pages**")
                st.caption("Cluster → Claude writes content → HTML export for kolo.xyz/crypto-card/*")
                st.caption("→ Go to Tab 3 (Build Pages)")

    # ── TAB 3: Build Pages ────────────────────────────────────────
    with tab_build:
        st.subheader("Build & Export Pages")
        st.info("Clusters keywords → Claude content → ready-to-deploy package.")

        api_key = st.session_state.get("anthropic_token")
        validated = st.session_state.get("pseo_validated")
        source = [kw for kw in validated if kw.get("demand_signal") in ("strong", "medium")] if validated else st.session_state.get("pseo_matrix")

        if not source:
            st.warning("Run Tab 1 (Keyword Matrix) first")
        else:
            st.write(f"**{len(source)}** keywords available")

            st.markdown("### Step 1 — Cluster into Pages")
            if st.button("📦 Cluster Keywords → Pages", type="primary"):
                clusters = cluster_keywords_to_pages(source)
                st.session_state["pseo_clusters"] = clusters

            if "pseo_clusters" in st.session_state:
                clusters = st.session_state["pseo_clusters"]
                st.success(f"**{len(clusters)}** pages (1 per country+language)")

                cluster_rows = [{"slug": c.slug, "primary_keyword": c.primary_keyword,
                    "secondary": len(c.secondary_keywords), "lang": c.lang,
                    "country": c.country_name, "template": c.template, "score": c.avg_score}
                    for c in clusters]
                st.dataframe(pd.DataFrame(cluster_rows), height=350, hide_index=True)

                st.markdown("### Step 2 — Generate Content (Claude API)")
                if not api_key:
                    st.warning("Enter Anthropic API key in sidebar")
                else:
                    model = st.selectbox("Model", ["claude-haiku-4-5-20251001", "claude-sonnet-4-6"], index=0,
                                         help="Haiku ≈ $0.002/page, Sonnet ≈ $0.01/page")
                    est_cost = len(clusters) * (0.002 if "haiku" in model else 0.01)
                    st.caption(f"Estimated cost: ~${est_cost:.2f} for {len(clusters)} pages")

                    if st.button("✍️ Generate All Content", type="primary"):
                        progress = st.progress(0)
                        def _update(i, total):
                            progress.progress(i / total, text=f"Page {i}/{total}: {clusters[i-1].slug}")
                        clusters = generate_content_batch(clusters, api_key, model=model, delay=1.0, progress_callback=_update)
                        progress.progress(1.0, text="Done!")
                        st.session_state["pseo_clusters"] = clusters
                        st.session_state["pseo_content_generated"] = True

                if st.session_state.get("pseo_content_generated"):
                    st.markdown("### Step 3 — Assemble & Export")
                    if st.button("🏗️ Build HTML Pages + Export Package", type="primary"):
                        clusters = st.session_state["pseo_clusters"]
                        clusters = build_all_pages(clusters)
                        st.session_state["pseo_clusters"] = clusters

                        base_dir = os.path.join(os.path.dirname(__file__) or ".", "..", "pages_export")
                        count = export_pages_local(clusters, base_dir)
                        _generate_designer_brief(clusters, base_dir)
                        st.success(f"**{count}** pages exported to `pages_export/`")
                        st.balloons()

                    if st.session_state.get("pseo_clusters") and st.session_state["pseo_clusters"][0].full_html:
                        clusters = st.session_state["pseo_clusters"]
                        st.markdown("### Preview")
                        preview_idx = st.selectbox("Select page", range(len(clusters)),
                            format_func=lambda i: f"{clusters[i].slug} — {clusters[i].h1}")
                        sel = clusters[preview_idx]
                        col1, col2 = st.columns(2)
                        with col1:
                            st.markdown(f"**Slug:** `/crypto-card/{sel.slug}`")
                            st.markdown(f"**Title:** {sel.title}")
                            st.markdown(f"**Primary:** {sel.primary_keyword}")
                            st.markdown(f"**Secondary:** {', '.join(sel.secondary_keywords[:5])}")
                        with col2:
                            st.markdown(f"**Lang:** {sel.lang}")
                            st.markdown(f"**Country:** {sel.country_name}")
                            st.markdown(f"**Template:** {sel.template}")
                            st.markdown(f"**Score:** {sel.avg_score:.3f}")

                        with st.expander("HTML Source", expanded=False):
                            st.code(sel.full_html[:5000], language="html")
                        st.components.v1.html(sel.full_html, height=700, scrolling=True)
